
[window]
decorations = "Full"
startup_mode = "Windowed"
dynamic_padding = true
dimensions = { columns = 192, lines = 55 }
padding = { x = 0, y = 0 }

[scrolling]
history = 25000
multiplier = 5

[mouse]
hide_when_typing = true

[font]
# size = 22
size = 13
normal = {family = "FiraCode Nerd Font Mono", style = "Regular"}
bold = {family = "FiraCode Nerd Font Mono", style = "Bold"}
italic = {family = "FiraCode Nerd Font Mono", style = "Regular"}
bold_italic = {family = "FiraCode Nerd Font Mono", style = "Bold"}

[terminal]
osc52 = "CopyPaste"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[shell]
program= "tmux"
args = ["new-session", "-A"]

